### PR TITLE
fix: Fractional evaluation

### LINKED ISSUE #40: TargetingKey in EvaluationContext is not converted
Since [EvaluationContext](https://github.com/open-feature/ruby-sdk/blob/27b2dab4fed0b348d0575c0909d4beeea376b27d/lib/open_feature/sdk/evaluation_context.rb#L8-L10) converts symbols to string 

```
      def initialize(**fields)
        @fields = fields.transform_keys(&:to_s)
      end
```

following [line](https://github.com/open-feature/ruby-sdk-contrib/blob/cb339983bf1e339255a252905c60f4d2c59ff758/providers/openfeature-flagd-provider/lib/openfeature/flagd/provider/client.rb#L101) doesn't work as intended

`fields["targetingKey"] = fields.delete(:targeting_key)`

### PR DESCRIPTION
**Pull request by augustinasrce**
## This PR

Fixes issues with fractional evaluation (when targeting_key is provided). It always resulted in error.

### Related Issues

[Fixes #40](https://github.com/open-feature/ruby-sdk-contrib/issues/40)

### CODE REVIEW

File: providers/openfeature-flagd-provider/spec/openfeature/flagd/provider_spec.rb [hunk 1]
```diff
@@ -123,17 +123,17 @@
...
         end
 
-        initial_value = fetch_value_with_targeting_key.call("123")
-        (0..2).to_a.each do # try with 1000
-          expect(fetch_value_with_targeting_key.call("123")).to eq(initial_value)
-        end
+        expect(fetch_value_with_targeting_key.call("1234")).to eq("#b91c1c")
+        expect(fetch_value_with_targeting_key.call("qwe")).to eq("#0284c7")
+        expect(fetch_value_with_targeting_key.call("abcd")).to eq("#16a34a")
+        expect(fetch_value_with_targeting_key.call("rfv")).to eq("#b91c1c")
```
Comment (augustinasrce) [inline providers/openfeature-flagd-provider/spec/openfeature/flagd/provider_spec.rb:136]: These values evaluates to four different variants. IMO it's better approach to test fractional, instead of doing multiple calls with same value. 

It was fallbacking to default value, thats why test was passing.

File: providers/openfeature-flagd-provider/lib/openfeature/flagd/provider/client.rb [hunk 2]
```diff
@@ -98,7 +98,7 @@ def prepare_evaluation_context(evaluation_context)
           return nil unless evaluation_context
 
           fields = evaluation_context.fields
-          fields["targetingKey"] = fields.delete(:targeting_key)
+          fields["targetingKey"] = fields.delete("targeting_key")
```
Comment (augustinasrce) [inline providers/openfeature-flagd-provider/lib/openfeature/flagd/provider/client.rb:101]: EvaluationContext on initialization converts all keys to string, thats why it wasn't working before.

**Comment by augustinasrce** [comment]
Check resolved comments for more details.

**Review by beeme1mr — APPROVED** [review]

**Review by alxckn — APPROVED** [review]
